package forum.entities;
// Generated 14 mars 2015 04:47:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comments generated by hbm2java
 * L'entité qui gère les commentaires des utilisateurs et des fils.
 */
@Entity
@Table(name="comments"
    ,catalog="forumdb"
)
public class Comments  implements java.io.Serializable {


     private Integer id;
     private Threads threads;
     private Users users;
     
     private String content;
     private boolean enabled;

    public Comments() {
        this.enabled = true;
    }

	
    public Comments(Threads threads, Users users, boolean enabled) {
        this.threads = threads;
        this.users = users;
        this.enabled = enabled;
    }
    public Comments(Threads threads, Users users, String content, boolean enabled) {
       this.threads = threads;
       this.users = users;
       this.content = content;
       this.enabled = enabled;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="thread_id", nullable=false)
    public Threads getThreads() {
        return this.threads;
    }
    
    public void setThreads(Threads threads) {
        this.threads = threads;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="content", length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="enabled", nullable=false)
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

}
