package forum.entities;
// Generated 14 mars 2015 04:47:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Threads generated by hbm2java
 * L'entité qui gère les fils(sujets).
 */
@Entity
@Table(name="threads"
    ,catalog="forumdb"
)
public class Threads  implements java.io.Serializable {


     private Integer id;
     private Users users;
     @NotEmpty
     private String title;
     @NotEmpty
     private String content;
     private boolean enabled;
     private Set commentses = new HashSet(0);

    public Threads() {
    }

	
    public Threads(Users users, boolean enabled) {
        this.users = users;
        this.enabled = enabled;
    }
    public Threads(Users users, String title, String content, boolean enabled, Set commentses) {
       this.users = users;
       this.title = title;
       this.content = content;
       this.enabled = enabled;
       this.commentses = commentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="content", length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="enabled", nullable=false)
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="threads")
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


